version: '3.4'

x-common-variables: &common-variables
{%- if cookiecutter.celery %}
  CELERY_BROKER_URL: redis://redis:6379
  CELERY_RESULT_BACKEND: redis://redis:6379
{%- endif %}
{%- if cookiecutter.mysql %}
  MYSQL_HOST: mysql
  MYSQL_ROOT_PASSWORD: mysql123
  MYSQL_USER: mysql
  MYSQL_PASSWORD: mysql123
  MYSQL_DATABASE: hse-api-database
{%- endif %}
 HSELING_RPC_ENDPOINT: http://hse-api-web:80/rpc/
 HSELING_API_ENDPOINT: http://hse-api-web:80/api/
 RESTRICTED_MODE: 0

services:
  hse-api-web:
    build:
      context: .
      dockerfile: hseling-api-{{cookiecutter.package_uri_part}}/Dockerfile
    ports:
      - "5000:80"
    volumes:
      - ./hseling-api-{{cookiecutter.package_uri_part}}/hseling_api_{{cookiecutter.package_name}}:/app/hseling_api_{{cookiecutter.package_name}}
    - type: bind
      source: ./hseling-data-{{cookiecutter.package_uri_part}}
      target: /data
    depends_on:
{%- if cookiecutter.mysql %}
      - mysql
{%- endif %}
{%- if cookiecutter.celery %}
      - redis
      - hse-api-celery
{%- endif %}
    environment: *common-variables
{% if cookiecutter.celery %}
  hse-api-celery:
    build:
      context: .
      dockerfile: hseling-api-{{cookiecutter.package_uri_part}}/Dockerfile
    command: celery -A main.celery worker
    volumes:
      - ./hseling-api-{{cookiecutter.package_uri_part}}/hseling_api_{{cookiecutter.package_name}}:/app/hseling_api_{{cookiecutter.package_name}}
    - type: bind
      source: ./hseling-data-{{cookiecutter.package_uri_part}}
      target: /data
    depends_on:
{%- if cookiecutter.mysql %}
      - mysql
{%- endif %}
      - redis
    environment: *common-variables
{%- endif %}

{% if cookiecutter.mysql %}
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: *common-variables
    volumes:
      - type: bind
        source: ./hseling-data-{{cookiecutter.package_uri_part}}/mysql
        target: /var/lib/mysql
{%- endif %}

{% if cookiecutter.celery %}
  redis:
    image: redis:latest
{%- endif %}

  hse-web-web:
    build:
      context: .
      dockerfile: hseling-web-{{cookiecutter.package_uri_part}}/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - hse-api-web
{%- if cookiecutter.celery %}
      - hse-api-celery
{%- endif %}
    environment: *common-variables
    volumes:
      - type: bind
        source: ./hseling-data-{{cookiecutter.package_uri_part}}/web
        target: /data

